# Site Settings
title:               Ms Faye
name:                "Ms Faye"
tagline:             veni vidi vici
description:         "The blog of Faye"
baseurl:            #"/Lagrange"
url:                 "chaosgsc.com"
github:
  url:               #"https://lenpaul.github.io/Lagrange"
author:
  name:              "Ms Faye"
  email:             "fayewong1991@gmail.com"
  twitter:           "Ssss74642806"
  instagram:         "acehhhhty"
  github:            "Darcygsc"
  facebook:          ""
  telegram:          ""
  spotify:           ""
  weixin:            ""
  weibo:             ""
  rss:               ""
  dribbble:          "Darcyy"
navigation:
- title: About
  url: /about
- title: Writings
  url: /writings

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:
  - jekyll-sitemap

#gems: [jekyll-paginate]
