# Site Settings
title:               Ms Faye
name:                "Ms Faye"
tagline:             veni vidi vici
description:         "The blog of Faye"
baseurl:            #"/Lagrange"
github:
  url:               #"https://lenpaul.github.io/Lagrange"
author:
  name:              "Ms Faye"
  email:             "fayewong1991@gmail.com"
  github:            "fayewong1991"
  facebook:          ""
  telegram:          ""
  spotify:           ""
  weixin:            ""
  weibo:             ""
  rss:               ""
#navigation:
#- title: About
#  url: /about
#- title: Writings
#  url: /writings

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:
  - jekyll-sitemap

gems: [jekyll-paginate]

# Sidebar settings
#sidebar: true                           # whether or not using Sidebar.
#sidebar-about-description: "For the next quantum leap<br>离开世界之前，一切都是过程"
#sidebar-avatar: /img/avatar-hux-ny.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value
